version: '3.4'

networks:
  frontend:
  backend:

services:
  eventcatalogapi:
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    image: event/catalogapi
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventLiteCatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:5678
    ports:
      - "5678:80"
    container_name: eventcatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1440:1433"
    container_name: eventsqlserver
    networks:
      - backend

  webmvc:
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    image: event/webmvc
    environment:
     EventCatalogApiUrl: http://eventcatalogapi
    ports:
     - "1337:80"
    container_name: eventwebmvc
    networks:
      - frontend
    depends_on:
      - eventcatalogapi
